package rulepack

// ValidATLAS reports whether id is a technique or sub-technique ID in the
// embedded MITRE ATLAS release (atlas_ids.go, regenerated by
// scripts/gen-atlas-ids.sh).
func ValidATLAS(id string) bool {
	_, ok := atlasTechniques[id]
	return ok
}

// ATLASName returns the technique name for id, or "" when unknown.
func ATLASName(id string) string {
	return atlasTechniques[id]
}
