// Code generated by go generate ./internal/fingerprint; DO NOT EDIT.

package fingerprint

const (
	parse    = "dea9ecafee34f2b3c54ec88676ca673691c061ccadbed29c13ab646125312485"
	analysis = "790b815b30c5ba2714b83c89e3ab8fa15303ebdb226e4a7fc2b9f46e5e10daa0"
)
