#!/usr/bin/env bash
# Regenerate docs/detection-coverage.md from the binary's own rule listing.
#
#   scripts/coverage-matrix.sh            # writes docs/detection-coverage.md
#
# Source of truth is `agentdfir rules list --packs rules --json`, i.e. the
# built-in catalog (internal/catalog) plus the shipped packs (rules/). Never
# edit the generated file by hand.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/docs/detection-coverage.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

(cd "$HERE" && go run ./cmd/agentdfir rules list --packs rules --json) > "$TMP"

ATLAS_VER="$(jq -r .atlas_version "$TMP")"
TOTAL="$(jq '.rules|length' "$TMP")"
BUILTIN="$(jq '[.rules[]|select(.source=="builtin")]|length' "$TMP")"
PACK="$(jq '[.rules[]|select(.source!="builtin")]|length' "$TMP")"
HIGHCRIT="$(jq '[.rules[]|select(.severity=="HIGH" or .severity=="CRITICAL")]|length' "$TMP")"
HIGHCRIT_MAPPED="$(jq '[.rules[]|select((.severity=="HIGH" or .severity=="CRITICAL") and ((.mitre_attack//"")!="" or (.mitre_atlas//"")!=""))]|length' "$TMP")"
ATLAS_TECH="$(jq '[.rules[].mitre_atlas|select(.!=null and .!="")]|unique|length' "$TMP")"
ATTACK_TECH="$(jq '[.rules[].mitre_attack|select(.!=null and .!="")]|unique|length' "$TMP")"

{
cat <<EOF
# Detection coverage: MITRE ATLAS and ATT&CK

<!-- GENERATED by scripts/coverage-matrix.sh from \`agentdfir rules list --packs rules --json\`. Do not edit. -->

| | |
|---|---|
| Rules (built-in + shipped packs) | **$TOTAL** ($BUILTIN built-in, $PACK in \`rules/\`) |
| HIGH / CRITICAL rules | $HIGHCRIT, of which **$HIGHCRIT_MAPPED** carry a MITRE mapping |
| Distinct MITRE ATLAS techniques covered | **$ATLAS_TECH** (ATLAS $ATLAS_VER) |
| Distinct MITRE ATT&CK techniques covered | **$ATTACK_TECH** |

Every HIGH/CRITICAL rule must map to at least one MITRE technique; every
\`mitre_atlas\` value must exist in the embedded ATLAS release. Both are
enforced by tests (\`internal/rulepack/mitre_test.go\`, \`internal/catalog\`).
The HIGH built-ins without a mapping (\`ORPHAN_AGENT\`, \`CROSS_SESSION_MESSAGE\`)
describe agent topology and evidence quality, not an adversary technique, and
are exempt by name in the catalog test.

Reproduce this table locally:

\`\`\`sh
agentdfir rules list --packs rules          # human-readable
agentdfir rules list --packs rules --json   # machine-readable
\`\`\`

## MITRE ATLAS techniques → rules

EOF

echo "| ATLAS technique | Name | Rules |"
echo "|---|---|---|"
jq -r '
  [.rules[] | select((.mitre_atlas//"")!="")]
  | group_by(.mitre_atlas)
  | .[]
  | "| `\(.[0].mitre_atlas)` | \(.[0].mitre_atlas_name) | " + ([.[] | "`\(.id)`" + (if .source=="builtin" then "" else " (\(.source))" end)] | join(", ")) + " |"
' "$TMP"

cat <<EOF

## MITRE ATT&CK techniques → rules

| ATT&CK technique | Rules |
|---|---|
EOF
jq -r '
  [.rules[] | select((.mitre_attack//"")!="")]
  | group_by(.mitre_attack)
  | .[]
  | "| [`\(.[0].mitre_attack)`](https://attack.mitre.org/techniques/\(.[0].mitre_attack|gsub("\\.";"/"))/) | " + ([.[] | "`\(.id)`" + (if .source=="builtin" then "" else " (\(.source))" end)] | join(", ")) + " |"
' "$TMP"

cat <<EOF

## All rules

| Severity | Rule | Surface | ATT&CK | ATLAS | Source |
|---|---|---|---|---|---|
EOF
jq -r '
  .rules
  | sort_by((if .severity=="CRITICAL" then 0 elif .severity=="HIGH" then 1 elif .severity=="MEDIUM" then 2 elif .severity=="LOW" then 3 else 4 end), .id)
  | .[]
  | "| \(.severity) | `\(.id)` | \(.surface) | \(if (.mitre_attack//"")=="" then "-" else .mitre_attack end) | \(if (.mitre_atlas//"")=="" then "-" else .mitre_atlas end) | \(.source) |"
' "$TMP"
} > "$OUT"

echo "wrote $OUT ($TOTAL rules, $ATLAS_TECH ATLAS / $ATTACK_TECH ATT&CK techniques)"
