// Package compute derives the code fingerprints the fingerprint package
// embeds. It is shared by the generator and the test that proves the
// embedded values are current.
package compute

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Roots are the packages whose dependency closures are fingerprinted.
var Roots = map[string]string{
	"parse":    "internal/normalize",
	"analysis": "internal/analysis",
}

// excluded packages never contribute: version changes every release
// without changing what any parser or rule does (SchemaVersion is keyed
// separately), and fingerprint would otherwise hash its own output.
var excluded = []string{"internal/version", "internal/fingerprint"}

type pkg struct {
	ImportPath string
	Dir        string
	Module     *struct{ Path string }
	EmbedFiles []string
}

// Compute returns the fingerprint of rel's in-module dependency closure,
// run from the module root.
//
// It must be the same on every OS and architecture, so the closure is
// listed for one fixed target and every non-test .go file in each
// package directory is hashed regardless of build tags, with line endings
// normalized (a Windows checkout with autocrlf must not change it).
func Compute(root, rel string) (string, error) {
	cmd := exec.Command("go", "list", "-deps", "-json", "./"+rel)
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=0", "GOFLAGS=-mod=mod")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("go list %s: %v: %s", rel, err, stderr.String())
	}
	modPath, err := modulePath(root)
	if err != nil {
		return "", err
	}
	var pkgs []pkg
	dec := json.NewDecoder(bytes.NewReader(out))
	for {
		var p pkg
		if err := dec.Decode(&p); err == io.EOF {
			break
		} else if err != nil {
			return "", err
		}
		if p.Module == nil || p.Module.Path != modPath {
			continue
		}
		relPkg := strings.TrimPrefix(strings.TrimPrefix(p.ImportPath, modPath), "/")
		skip := false
		for _, x := range excluded {
			if relPkg == x || strings.HasPrefix(relPkg, x+"/") {
				skip = true
			}
		}
		if !skip {
			p.ImportPath = relPkg
			pkgs = append(pkgs, p)
		}
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].ImportPath < pkgs[j].ImportPath })

	h := sha256.New()
	for _, p := range pkgs {
		files, err := filepath.Glob(filepath.Join(p.Dir, "*.go"))
		if err != nil {
			return "", err
		}
		for _, e := range p.EmbedFiles {
			files = append(files, filepath.Join(p.Dir, filepath.FromSlash(e)))
		}
		names := make([]string, 0, len(files))
		for _, f := range files {
			if strings.HasSuffix(f, "_test.go") {
				continue
			}
			r, err := filepath.Rel(p.Dir, f)
			if err != nil {
				return "", err
			}
			names = append(names, filepath.ToSlash(r))
		}
		sort.Strings(names)
		for _, n := range names {
			data, err := os.ReadFile(filepath.Join(p.Dir, filepath.FromSlash(n)))
			if err != nil {
				return "", err
			}
			data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
			fmt.Fprintf(h, "%s/%s\x00%d\x00", p.ImportPath, n, len(data))
			h.Write(data)
		}
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func modulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(data), "\n") {
		if f := strings.Fields(line); len(f) == 2 && f[0] == "module" {
			return f[1], nil
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

// Source renders the generated Go file.
func Source(parse, analysis string) string {
	return fmt.Sprintf(`// Code generated by go generate ./internal/fingerprint; DO NOT EDIT.

package fingerprint

const (
	parse    = %q
	analysis = %q
)
`, parse, analysis)
}
